version: '3'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - gaaspard-main

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - gaaspard-main

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8082:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"
    networks:
      - gaaspard-main

  grafana:
    image: grafana/grafana
    ports:
      - '3035:3000'
    depends_on:
      - prometheus
      - loki
    restart: always
    networks:
      - gaaspard-main



  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   command: -config.file=/etc/loki/local-config.yaml
  #   ports:
  #     - '3100:3100'
  #   volumes:
  #     - ./loki-local-config.yaml:/etc/loki/local-config.yaml
  #   networks:
  #     - gaaspard-main

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config.yaml:/etc/promtail/config.yaml
  #     # on monte en lecture seule le dossier hébergeant votre log Dolibarr
  #     - ../gaaspard/dolibarr_logs:/var/log/dolibarr:ro
  #   depends_on:
  #     - loki
  #   networks:
  #     - gaaspard-main

volumes:
  prometheus_data: {}

networks:
  gaaspard-main:
    name: gaaspard_default
    external: true
